// Package domain contains the core business entities for meowpayments.
package domain

import (
	"time"

	"github.com/google/uuid"
	"github.com/meowpayments/meowpayments/internal/oneclick"
	"github.com/shopspring/decimal"
)

// Payment represents a crypto payment request.
// The operator creates a payment specifying what token/chain they want to receive
// and at which address. The customer sends any supported token to the deposit
// address generated by the NEAR Intents 1-click API.
type Payment struct {
	ID uuid.UUID

	// --- Destination (what the operator wants to receive) ---
	// DestAssetID is a defuse asset identifier, e.g. "nep141:usdc.near"
	DestAssetID string
	// DestChain is the blockchain name, e.g. "near", "eth", "sol"
	DestChain string
	// DestAddress is the on-chain address tokens are delivered to.
	DestAddress string
	// OriginAssetID is the asset the customer is sending, e.g. "nep141:sol-usdc...".
	// Empty means ANY_INPUT (any token accepted).
	OriginAssetID string

	// --- Amount (operator sets one of these) ---
	// AmountUSD is the expected USD value of the payment (optional).
	// If set, displayed to the customer for guidance only - since we use ANY_INPUT
	// the actual amount received may differ.
	AmountUSD *decimal.Decimal
	// AmountAsset is the expected amount in destination token raw units (optional).
	AmountAsset *decimal.Decimal
	// AmountSymbol is the human-readable symbol for AmountAsset, e.g. "USDC".
	AmountSymbol string

	// --- Deposit side (set after quote is obtained) ---
	DepositAddress string
	DepositMemo    string // required for some chains (TON, XRP, etc.)
	QuoteExpiresAt *time.Time

	// --- Lifecycle ---
	Status         oneclick.PaymentStatus
	OneclickStatus string // raw status string from upstream
	FailureReason  string

	// --- Callback / metadata ---
	CallbackURL   string
	Metadata      map[string]any
	CustomerEmail string

	ExpiresAt time.Time

	// --- Polling bookkeeping ---
	LastPolledAt *time.Time
	PollFailures int

	CreatedAt time.Time
	UpdatedAt time.Time
}

// NeedsPolling returns true if this payment should be polled for status updates.
func (p *Payment) NeedsPolling() bool {
	return p.DepositAddress != "" && !p.Status.IsTerminal()
}

// IsTerminal returns true when no further status transitions are expected.
func (p *Payment) IsTerminal() bool {
	return p.Status.IsTerminal()
}

// PaymentURL builds the customer-facing payment link.
func (p *Payment) PaymentURL(baseURL string) string {
	return baseURL + "/pay/" + p.ID.String()
}

// PaymentEvent is an immutable record of a status transition or notable event.
type PaymentEvent struct {
	ID        int64
	PaymentID uuid.UUID
	EventType string
	OldStatus oneclick.PaymentStatus
	NewStatus oneclick.PaymentStatus
	Payload   map[string]any
	CreatedAt time.Time
}

const (
	EventStatusChange    = "status_change"
	EventDepositDetected = "deposit_detected"
	EventCallbackSent    = "callback_sent"
	EventCallbackFailed  = "callback_failed"
	EventError           = "error"
)
